/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AppCompassRouteImport } from './routes/_app/compass'
import { Route as AppInfluenceRouteImport } from './routes/_app/influence'
import { Route as AppInsightsRouteImport } from './routes/_app/insights'
import { Route as AppJournalRouteImport } from './routes/_app/journal'
import { Route as AppMatrixRouteImport } from './routes/_app/matrix'
import { Route as AppRolesRouteImport } from './routes/_app/roles'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStewardshipsRouteImport } from './routes/_app/stewardships'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppTodayRouteImport } from './routes/_app/today'
import { Route as AppPlanStartRouteImport } from './routes/_app/plan.$start'
import { Route as AppWeekIndexRouteImport } from './routes/_app/week.index'
import { Route as AppWeekStartRouteImport } from './routes/_app/week.$start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCompassRoute = AppCompassRouteImport.update({
  id: '/compass',
  path: '/compass',
  getParentRoute: () => AppRoute,
} as any)
const AppInfluenceRoute = AppInfluenceRouteImport.update({
  id: '/influence',
  path: '/influence',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppMatrixRoute = AppMatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStewardshipsRoute = AppStewardshipsRouteImport.update({
  id: '/stewardships',
  path: '/stewardships',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanStartRoute = AppPlanStartRouteImport.update({
  id: '/plan/$start',
  path: '/plan/$start',
  getParentRoute: () => AppRoute,
} as any)
const AppWeekIndexRoute = AppWeekIndexRouteImport.update({
  id: '/week/',
  path: '/week/',
  getParentRoute: () => AppRoute,
} as any)
const AppWeekStartRoute = AppWeekStartRouteImport.update({
  id: '/week/$start',
  path: '/week/$start',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/compass': typeof AppCompassRoute
  '/influence': typeof AppInfluenceRoute
  '/insights': typeof AppInsightsRoute
  '/journal': typeof AppJournalRoute
  '/matrix': typeof AppMatrixRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/stewardships': typeof AppStewardshipsRoute
  '/tasks': typeof AppTasksRoute
  '/today': typeof AppTodayRoute
  '/plan/$start': typeof AppPlanStartRoute
  '/week/$start': typeof AppWeekStartRoute
  '/week/': typeof AppWeekIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/compass': typeof AppCompassRoute
  '/influence': typeof AppInfluenceRoute
  '/insights': typeof AppInsightsRoute
  '/journal': typeof AppJournalRoute
  '/matrix': typeof AppMatrixRoute
  '/roles': typeof AppRolesRoute
  '/settings': typeof AppSettingsRoute
  '/stewardships': typeof AppStewardshipsRoute
  '/tasks': typeof AppTasksRoute
  '/today': typeof AppTodayRoute
  '/plan/$start': typeof AppPlanStartRoute
  '/week/$start': typeof AppWeekStartRoute
  '/week': typeof AppWeekIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/_app/compass': typeof AppCompassRoute
  '/_app/influence': typeof AppInfluenceRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/matrix': typeof AppMatrixRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/stewardships': typeof AppStewardshipsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/today': typeof AppTodayRoute
  '/_app/plan/$start': typeof AppPlanStartRoute
  '/_app/week/$start': typeof AppWeekStartRoute
  '/_app/week/': typeof AppWeekIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/welcome'
    | '/compass'
    | '/influence'
    | '/insights'
    | '/journal'
    | '/matrix'
    | '/roles'
    | '/settings'
    | '/stewardships'
    | '/tasks'
    | '/today'
    | '/plan/$start'
    | '/week/$start'
    | '/week/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome'
    | '/compass'
    | '/influence'
    | '/insights'
    | '/journal'
    | '/matrix'
    | '/roles'
    | '/settings'
    | '/stewardships'
    | '/tasks'
    | '/today'
    | '/plan/$start'
    | '/week/$start'
    | '/week'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/welcome'
    | '/_app/compass'
    | '/_app/influence'
    | '/_app/insights'
    | '/_app/journal'
    | '/_app/matrix'
    | '/_app/roles'
    | '/_app/settings'
    | '/_app/stewardships'
    | '/_app/tasks'
    | '/_app/today'
    | '/_app/plan/$start'
    | '/_app/week/$start'
    | '/_app/week/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/compass': {
      id: '/_app/compass'
      path: '/compass'
      fullPath: '/compass'
      preLoaderRoute: typeof AppCompassRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/influence': {
      id: '/_app/influence'
      path: '/influence'
      fullPath: '/influence'
      preLoaderRoute: typeof AppInfluenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/matrix': {
      id: '/_app/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof AppMatrixRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stewardships': {
      id: '/_app/stewardships'
      path: '/stewardships'
      fullPath: '/stewardships'
      preLoaderRoute: typeof AppStewardshipsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plan/$start': {
      id: '/_app/plan/$start'
      path: '/plan/$start'
      fullPath: '/plan/$start'
      preLoaderRoute: typeof AppPlanStartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/week/': {
      id: '/_app/week/'
      path: '/week'
      fullPath: '/week/'
      preLoaderRoute: typeof AppWeekIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/week/$start': {
      id: '/_app/week/$start'
      path: '/week/$start'
      fullPath: '/week/$start'
      preLoaderRoute: typeof AppWeekStartRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCompassRoute: typeof AppCompassRoute
  AppInfluenceRoute: typeof AppInfluenceRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppJournalRoute: typeof AppJournalRoute
  AppMatrixRoute: typeof AppMatrixRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStewardshipsRoute: typeof AppStewardshipsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTodayRoute: typeof AppTodayRoute
  AppPlanStartRoute: typeof AppPlanStartRoute
  AppWeekStartRoute: typeof AppWeekStartRoute
  AppWeekIndexRoute: typeof AppWeekIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCompassRoute: AppCompassRoute,
  AppInfluenceRoute: AppInfluenceRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppJournalRoute: AppJournalRoute,
  AppMatrixRoute: AppMatrixRoute,
  AppRolesRoute: AppRolesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStewardshipsRoute: AppStewardshipsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTodayRoute: AppTodayRoute,
  AppPlanStartRoute: AppPlanStartRoute,
  AppWeekStartRoute: AppWeekStartRoute,
  AppWeekIndexRoute: AppWeekIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
